--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: currencycloudapigateway
    version: v1
  name: currencycloudapigateway
spec: 
  ports: 
    - 
      name: http
      port: 8090
      targetPort: 8090
  selector: 
    app: currencycloudapigateway
    version: v1
  type: NodePort